### ISSUE TITLE
Add option to show directories first

### ISSUE THREAD

**Issue by anuvyklack** [elihunter173/dirbuf.nvim#11] opened 2022-01-17 22:37 UTC
All in the title. Like in `ls`.

**Comment by elihunter173** [comment] 2022-01-17 22:39
Duplicate of #5 . See [`sort-option`](https://github.com/elihunter173/dirbuf.nvim/tree/sort-option) branch. Will likely be merged soon

**Closed by elihunter173** 2022-01-17 22:39 UTC
Labels: duplicate
