### ISSUE TITLE
dirbuf.nvim BufEnter handler conflicts with nvim-tree.lua

### ISSUE THREAD

**Issue by lalitmee** [elihunter173/dirbuf.nvim#2] opened 2022-01-17 05:07 UTC
It shows me this error.

![image](https://user-images.githubusercontent.com/10762218/149711159-c320fcf0-8c74-4dc2-b06a-9159a8809172.png)

Don't know why.

**Comment by elihunter173** [comment] 2022-01-17 13:56
Could you show me the output of `nvim --version`?

**Comment by nagy135** [comment] 2022-01-17 16:18
same here. Just installed and opened random directory with simple `nvim .` and got this
```
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua /home/infiniter/.vim/plugged/dirbuf.nvim
id: 1
stack traceback:
        [C]: in function 'nvim_buf_set_name'
        /home/infiniter/.vim/plugged/dirbuf.nvim/lua/dirbuf.lua:90:
        [string ":lua"]:1: in main chunk
```

my setup is regular arch linux neovim release

```
❯ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.0.5
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

**Comment by elihunter173** [comment] 2022-01-17 20:07
@nagy135 I managed to reproduce your issue by pulling your nvim config. The issue was resolved when I uninstalled `nvim-tree.lua` (with `:PlugClean`). It seems that both dirbuf and nvim-tree are fighting over who gets to open directories. I'm currently looking into a fix

**Comment by elihunter173** [comment] 2022-01-17 20:22
@lalitmee I believe I've identified the same issue in your config. See if removing `nvim-tree.lua` fixes the issue for you as well

**Comment by nagy135** [comment] 2022-01-18 06:25
i will verify further but i would guess the same thing, since i think i saw nvim tree in those logs (i think). imho what would be awesome if you went vidir's aproach where its separate program that puts to vim's runtime only whats needed. Because there are multiple "tree plugins" that are awesome and this one doesnt feel like it should compete...it should compete with vidir. But these are just my opinions, its your call.

**Comment by lalitmee** [comment] 2022-01-18 11:13
Hey @elihunter173, sorry for late reply. But here it is:

- `nvim --version`
```
NVIM v0.7.0-dev+873-gf92a2457c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/lalitmee/Desktop/Github/neovim/build/config -I/home/lalitmee/Desktop/Github/neovim/src -I/home/lalitmee/Desktop/Github/neovim/.deps/usr/include -I/usr/include -I/home/lalitmee/Desktop/Github/neovim/build/src/nvim/auto -I/home/lalitmee/Desktop/Github/neovim/build/include
Compiled by lalitmee@pop-os

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

**Comment by nagy135** [comment] 2022-01-18 16:49
Verified, completely removed nvim-tree from my setup and it no longer shows said error ...hopefully you will figure out how to separate this!

**Comment by elihunter173** [comment] 2022-01-19 00:18
@nagy135 
> imho what would be awesome if you went vidir's aproach where its separate program that puts to vim's runtime only whats needed

That's fair but this is not the direction I want dirbuf to go in. I really enjoy it as a Netrw/dirvish style of plugin for navigating with vidir-like editing

I am looking for a way for dirbuf and nvim-tree to coexist tho, since I think it's reasonable to have both installed. Having some difficulty because I'm not too familiar with nvim-tree and it's internals

**Comment by elihunter173** [comment] 2022-01-19 00:43
@lalitmee @nagy135 I found the issue.

It has to do with the `:help nvim-tree.update_to_buf_dir` option. nvim-tree has the same incompatibility with `vim-dirvish` (which makes sense because dirbuf uses nearly identical vimscript). The fix is to update your config to disable `update_to_buf_dir` in nvim-tree like so
```lua
require"nvim-tree".setup {
  update_to_buf_dir = {
    enable = false,
  }
}
```

I'm going to add a warning to the README and help doc and open a PR on nvim-tree.lua to mention `nvim-tree.update_to_buf_dir`'s incompatibility with dirbuf.nvim alongside it's warning about vim-dirvish

**Comment by elihunter173** [comment] 2022-01-19 01:34
I've added a notice to the installation section in the README f3519f6d6a2aa771e24275e64508e0c51c49fe8d, so I'm closing this issue since the option change I mentioned above fixes all issues I can find

See https://github.com/kyazdani42/nvim-tree.lua/pull/901 for updates the nvim-tree.lua side of things

**Comment by lalitmee** [comment] 2022-01-27 13:27
@elihunter173, I still get this error after making the above change.

```
E5108: Error executing lua ...e/nvim/site/pack/packer/start/dirbuf.nvim/lua/dirbuf.lua:116: Vim(lua):E5108: Error executing lua ...e/nvim/site/pack/packer/start/dirbuf.nvim/lua/dirbuf.lua:82: Invalid buffer id: 32
stack traceback:
	[C]: in function 'nvim_buf_set_name'
	...e/nvim/site/pack/packer/start/dirbuf.nvim/lua/dirbuf.lua:82: in function 'edit_dirbuf'
	[string ":lua"]:1: in main chunk
	[C]: in function 'nvim_win_set_buf'
	...e/nvim/site/pack/packer/start/dirbuf.nvim/lua/dirbuf.lua:116: in function 'open'
	[string ":lua"]:1: in main chunk
stack traceback:
	[C]: in function 'nvim_win_set_buf'
	...e/nvim/site/pack/packer/start/dirbuf.nvim/lua/dirbuf.lua:116: in function 'open'
	[string ":lua"]:1: in main chunk
```

Can you please have a look at this and let me know what is happening?

**Comment by elihunter173** [comment] 2022-01-27 17:25
Hi @lalitmee . Please provide a minimal config to reproduce the error so I can fix it

I tried to pull down [your config](https://github.com/lalitmee/dotfiles/tree/master/nvim/.config/nvim) and spend roughly an hour wrestling with it. But considering it is roughly 20x larger than Dirbuf itself is, seems to be out of date based on the most recent modification, and has hardcoded paths at various places, I am giving up on that approach

**Comment by lalitmee** [comment] 2022-01-28 22:23
I am not sure how to check it with minimal config but in my config, you were looking at a different branch. The config which I am using is this [config](https://github.com/lalitmee/dotfiles/tree/lsp/coc.nvim/nvim/.config/nvim)

**Comment by elihunter173** [comment] 2022-01-29 04:22
@lalitmee Caught a typo! `update_to_bug_dir` instead of `update_to_buf_dir` https://github.com/lalitmee/dotfiles/blob/8191487c4021ee9facdf215cf932fae9ae71acce/nvim/.config/nvim/lua/lk/plugins/nvim-tree.lua#L46

That being said, there does seem to be a conflict with `lir.nvim`. I'm working on making a minimal config, but this is the error I see
```
E5108: Error executing lua ...e/nvim/site/pack/packer/start/dirbuf.nvim/lua/dirbuf.lua:43: Buffer is not 'modifiable'
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...e/nvim/site/pack/packer/start/dirbuf.nvim/lua/dirbuf.lua:43: in function 'fill_dirbuf'
        ...e/nvim/site/pack/packer/start/dirbuf.nvim/lua/dirbuf.lua:114: in function 'open'
        [string ":lua"]:1: in main chunk
```

**Comment by elihunter173** [comment] 2022-01-29 04:51
Alright, for the `lir.nvim` bug it is again lir and dirbuf have conflicting `BufEnter` autocommands. The best way to resolve this would be to pick one to keep and uninstall the other, since they serve basically the same purpose.

As far as I can tell, there's not a good way to have both be installed and usable. If you really want both installed, then you can add the following to forcibly disable lir's autocommands. I think this breaks lir, but it does leave Dirbuf fully functioning.
```vim
autocmd VimEnter * autocmd! lir
```

You can also disable dirbuf's autocommands like this. By itself, this would leave Dirbuf working except without `:edit .` opening dirbufs, but lir's `BufEnter` autocommand conflicts with this.
```vim
autocmd VimEnter * autocmd! dirbuf
```

You might be able to use both if you disable both of lir's and dirbuf's autocommands, assuming you find a way to use lir without its autocommands

**Comment by elihunter173** [comment] 2022-02-12 00:03
@lalitmee Any updates? Did the `lir.nvim` fix work?

**Comment by elihunter173** [comment] 2022-03-19 21:54
Closing due to inactivity. Please re-open if the fix I provided doesn't work or make a new issue if you face any new problems. Thanks!

**Closed by elihunter173** 2022-03-19 21:54 UTC
Labels: bug
